# Generated by Django 3.2.16 on 2024-12-16 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterattack',
            options={},
        ),
        migrations.AlterModelOptions(
            name='playercharacterrank',
            options={},
        ),
        migrations.AlterModelOptions(
            name='playerserver',
            options={},
        ),
    ]
