# Generated by Django 3.2.16 on 2024-12-16 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_app', '0002_auto_20241217_0202'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='characterattack',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='playercharacterrank',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='playerserver',
            options={'managed': False},
        ),
    ]
