# Generated by Django 3.2.16 on 2024-12-16 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_app', '0003_auto_20241217_0206'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamecharacter',
            options={},
        ),
    ]
