# Generated by Django 3.2.16 on 2024-12-16 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_app', '0004_alter_gamecharacter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gamecharacter',
            options={'managed': True},
        ),
    ]
