# Generated by Django 3.2.16 on 2024-12-16 23:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_app', '0005_alter_gamecharacter_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attack',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='characterattack',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='playercharacterrank',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='playerserver',
            options={'managed': True},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'managed': True},
        ),
    ]
