# Generated by Django 3.2.16 on 2024-12-16 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('table_app', '0006_auto_20241217_0228'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attack',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='characterattack',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='gamecharacter',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='player',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='playercharacterrank',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='playerserver',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='server',
            options={'managed': False},
        ),
    ]
